2025-05-25 23:23:43,433 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token, form=form))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
TypeError: hidden_tag() missing 1 required positional argument: 'self'
2025-05-25 23:27:14,309 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:27:21,967 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-25 23:27:55,555 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:28:01,469 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token, form=form))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
TypeError: hidden_tag() missing 1 required positional argument: 'self'
2025-05-25 23:32:25,335 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:33:27,078 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNzQ4MjA1NzUzLjA1MjI3MzV9.LNC0730RxyB1cGUsWIa0LptvW_ChH5LqAS5ONZ0dopk [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 223, in reset_password
    return render_template('reset_password.html', form=form)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\myblog\myenv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password.html
2025-05-25 23:34:51,681 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
